"""Add CommunityPost

Revision ID: 34ecd09e7dc8
Revises: 4b4d5c638902
Create Date: 2026-04-11 22:16:05.265536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34ecd09e7dc8'
down_revision = '4b4d5c638902'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('community_post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_community_post_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_post_song_id'), ['song_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_post_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community_post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_community_post_user_id'))
        batch_op.drop_index(batch_op.f('ix_community_post_song_id'))
        batch_op.drop_index(batch_op.f('ix_community_post_created_at'))

    op.drop_table('community_post')
    # ### end Alembic commands ###
