"""Reset_All

Revision ID: 62ff4e510e73
Revises: 
Create Date: 2026-04-01 09:12:05.404365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62ff4e510e73'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('media_url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_story_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_story_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_story_user_id'))
        batch_op.drop_index(batch_op.f('ix_story_created_at'))

    op.drop_table('story')
    # ### end Alembic commands ###
