"""Update naming convention for SQLite

Revision ID: 92549f581b78
Revises: 1b51be6a0771
Create Date: 2026-04-12 22:02:02.660172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92549f581b78'
down_revision = '1b51be6a0771'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_blend', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('partner_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('invitation_accepted', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_playlist_partner_id_user'), 'user', ['partner_id'], ['id'])

    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_song_file_path'), ['file_path'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_song_file_path'), type_='unique')

    with op.batch_alter_table('playlist', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_playlist_partner_id_user'), type_='foreignkey')
        batch_op.drop_column('invitation_accepted')
        batch_op.drop_column('partner_id')
        batch_op.drop_column('is_blend')

    # ### end Alembic commands ###
